apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: managment-system
  labels:
    app: backend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: tahseen176/college-managmet-system-backen:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-uri
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: managment-system
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      protocol: TCP
  type: ClusterIP
